<?php
/**
 * DomainListingAdminServiceV1ModelListingReport
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DomainListingAdminServiceV1ModelListingReport Class Doc Comment
 *
 * @category Class
 * @description Represent current listing status and aggregation of status messages
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DomainListingAdminServiceV1ModelListingReport implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Domain.ListingAdminService.v1.Model.ListingReport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'process_status' => 'string',
        'agency_id' => 'int',
        'provider_id' => 'string',
        'provider_ad_id' => 'string',
        'ad_id' => 'int[]',
        'quality_score' => 'int',
        'events' => '\Swagger\Client\Model\DomainListingAdminServiceV1ModelModelEvent[]',
        'versions' => '\Swagger\Client\Model\DomainListingAdminServiceV1ModelReportVersion[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'process_status' => null,
        'agency_id' => 'int64',
        'provider_id' => null,
        'provider_ad_id' => null,
        'ad_id' => 'int64',
        'quality_score' => 'int32',
        'events' => null,
        'versions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'process_status' => 'processStatus',
        'agency_id' => 'agencyId',
        'provider_id' => 'providerId',
        'provider_ad_id' => 'providerAdId',
        'ad_id' => 'adId',
        'quality_score' => 'qualityScore',
        'events' => 'events',
        'versions' => 'versions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'process_status' => 'setProcessStatus',
        'agency_id' => 'setAgencyId',
        'provider_id' => 'setProviderId',
        'provider_ad_id' => 'setProviderAdId',
        'ad_id' => 'setAdId',
        'quality_score' => 'setQualityScore',
        'events' => 'setEvents',
        'versions' => 'setVersions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'process_status' => 'getProcessStatus',
        'agency_id' => 'getAgencyId',
        'provider_id' => 'getProviderId',
        'provider_ad_id' => 'getProviderAdId',
        'ad_id' => 'getAdId',
        'quality_score' => 'getQualityScore',
        'events' => 'getEvents',
        'versions' => 'getVersions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PROCESS_STATUS_QUEUED = 'queued';
    const PROCESS_STATUS_PROCESSING = 'processing';
    const PROCESS_STATUS_PROCESSED = 'processed';
    const PROCESS_STATUS_SEARCHABLE = 'searchable';
    const PROCESS_STATUS_FAILED = 'failed';
    const PROCESS_STATUS_ERROR = 'error';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProcessStatusAllowableValues()
    {
        return [
            self::PROCESS_STATUS_QUEUED,
            self::PROCESS_STATUS_PROCESSING,
            self::PROCESS_STATUS_PROCESSED,
            self::PROCESS_STATUS_SEARCHABLE,
            self::PROCESS_STATUS_FAILED,
            self::PROCESS_STATUS_ERROR,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['process_status'] = isset($data['process_status']) ? $data['process_status'] : null;
        $this->container['agency_id'] = isset($data['agency_id']) ? $data['agency_id'] : null;
        $this->container['provider_id'] = isset($data['provider_id']) ? $data['provider_id'] : null;
        $this->container['provider_ad_id'] = isset($data['provider_ad_id']) ? $data['provider_ad_id'] : null;
        $this->container['ad_id'] = isset($data['ad_id']) ? $data['ad_id'] : null;
        $this->container['quality_score'] = isset($data['quality_score']) ? $data['quality_score'] : null;
        $this->container['events'] = isset($data['events']) ? $data['events'] : null;
        $this->container['versions'] = isset($data['versions']) ? $data['versions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getProcessStatusAllowableValues();
        if (!is_null($this->container['process_status']) && !in_array($this->container['process_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'process_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets process_status
     *
     * @return string
     */
    public function getProcessStatus()
    {
        return $this->container['process_status'];
    }

    /**
     * Sets process_status
     *
     * @param string $process_status Status of listing been processed  * Queued - We received request  * Processing - Request been processed  * Processed - Successful processed request  * Failed - Processing failed  * Error - Individual errors encountered
     *
     * @return $this
     */
    public function setProcessStatus($process_status)
    {
        $allowedValues = $this->getProcessStatusAllowableValues();
        if (!is_null($process_status) && !in_array($process_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'process_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['process_status'] = $process_status;

        return $this;
    }

    /**
     * Gets agency_id
     *
     * @return int
     */
    public function getAgencyId()
    {
        return $this->container['agency_id'];
    }

    /**
     * Sets agency_id
     *
     * @param int $agency_id AgencyId from Domain
     *
     * @return $this
     */
    public function setAgencyId($agency_id)
    {
        $this->container['agency_id'] = $agency_id;

        return $this;
    }

    /**
     * Gets provider_id
     *
     * @return string
     */
    public function getProviderId()
    {
        return $this->container['provider_id'];
    }

    /**
     * Sets provider_id
     *
     * @param string $provider_id ProviderId for the agency
     *
     * @return $this
     */
    public function setProviderId($provider_id)
    {
        $this->container['provider_id'] = $provider_id;

        return $this;
    }

    /**
     * Gets provider_ad_id
     *
     * @return string
     */
    public function getProviderAdId()
    {
        return $this->container['provider_ad_id'];
    }

    /**
     * Sets provider_ad_id
     *
     * @param string $provider_ad_id Listing identifier provided by CRM
     *
     * @return $this
     */
    public function setProviderAdId($provider_ad_id)
    {
        $this->container['provider_ad_id'] = $provider_ad_id;

        return $this;
    }

    /**
     * Gets ad_id
     *
     * @return int[]
     */
    public function getAdId()
    {
        return $this->container['ad_id'];
    }

    /**
     * Sets ad_id
     *
     * @param int[] $ad_id Advertisement Id from domain
     *
     * @return $this
     */
    public function setAdId($ad_id)
    {
        $this->container['ad_id'] = $ad_id;

        return $this;
    }

    /**
     * Gets quality_score
     *
     * @return int
     */
    public function getQualityScore()
    {
        return $this->container['quality_score'];
    }

    /**
     * Sets quality_score
     *
     * @param int $quality_score Quality score of the listing, based on data completeness
     *
     * @return $this
     */
    public function setQualityScore($quality_score)
    {
        $this->container['quality_score'] = $quality_score;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \Swagger\Client\Model\DomainListingAdminServiceV1ModelModelEvent[]
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \Swagger\Client\Model\DomainListingAdminServiceV1ModelModelEvent[] $events All Events associated with this processing request
     *
     * @return $this
     */
    public function setEvents($events)
    {
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets versions
     *
     * @return \Swagger\Client\Model\DomainListingAdminServiceV1ModelReportVersion[]
     */
    public function getVersions()
    {
        return $this->container['versions'];
    }

    /**
     * Sets versions
     *
     * @param \Swagger\Client\Model\DomainListingAdminServiceV1ModelReportVersion[] $versions version list
     *
     * @return $this
     */
    public function setVersions($versions)
    {
        $this->container['versions'] = $versions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
