<?php
/**
 * PreMarketV1PrePortalListingStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PreMarketV1PrePortalListingStatus Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PreMarketV1PrePortalListingStatus
{
    /**
     * Possible values of this enum
     */
    const PRE_MARKET = 'preMarket';
    const SOLD = 'sold';
    const LISTED = 'listed';
    const WITHDRAWN = 'withdrawn';
    const DRAFT = 'draft';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRE_MARKET
            self::SOLD
            self::LISTED
            self::WITHDRAWN
            self::DRAFT
        ];
    }
}
