<?php
/**
 * AddressLocatorsV1AddressDataModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * AddressLocatorsV1AddressDataModelTest Class Doc Comment
 *
 * @category    Class
 * @description APMAPIModelsTokenisedSearchV3AddressDataModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressLocatorsV1AddressDataModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddressLocatorsV1AddressDataModel"
     */
    public function testAddressLocatorsV1AddressDataModel()
    {
    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {
    }

    /**
     * Test attribute "address_components"
     */
    public function testPropertyAddressComponents()
    {
    }

    /**
     * Test attribute "ids"
     */
    public function testPropertyIds()
    {
    }
}
