<?php
/**
 * AgenciesV2AgencySummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * AgenciesV2AgencySummaryTest Class Doc Comment
 *
 * @category    Class
 * @description AgencySummary
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgenciesV2AgencySummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AgenciesV2AgencySummary"
     */
    public function testAgenciesV2AgencySummary()
    {
    }

    /**
     * Test attribute "in_suburb"
     */
    public function testPropertyInSuburb()
    {
    }

    /**
     * Test attribute "query_suburb"
     */
    public function testPropertyQuerySuburb()
    {
    }

    /**
     * Test attribute "has_recently_sold"
     */
    public function testPropertyHasRecentlySold()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {
    }

    /**
     * Test attribute "base_url"
     */
    public function testPropertyBaseUrl()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "rental_telephone"
     */
    public function testPropertyRentalTelephone()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "rental_email"
     */
    public function testPropertyRentalEmail()
    {
    }

    /**
     * Test attribute "home_page_search_options"
     */
    public function testPropertyHomePageSearchOptions()
    {
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
    }

    /**
     * Test attribute "number_for_sale"
     */
    public function testPropertyNumberForSale()
    {
    }

    /**
     * Test attribute "number_for_rent"
     */
    public function testPropertyNumberForRent()
    {
    }

    /**
     * Test attribute "domain_url"
     */
    public function testPropertyDomainUrl()
    {
    }

    /**
     * Test attribute "show_tab_sold_last_year"
     */
    public function testPropertyShowTabSoldLastYear()
    {
    }
}
