<?php
/**
 * DomainLocationProfilesServiceV1ModelLocationDataPropertyCategoriesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainLocationProfilesServiceV1ModelLocationDataPropertyCategoriesTest Class Doc Comment
 *
 * @category    Class
 * @description DomainLocationProfilesServiceV1ModelLocationDataPropertyCategories
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainLocationProfilesServiceV1ModelLocationDataPropertyCategoriesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainLocationProfilesServiceV1ModelLocationDataPropertyCategories"
     */
    public function testDomainLocationProfilesServiceV1ModelLocationDataPropertyCategories()
    {
    }

    /**
     * Test attribute "luxury_level_price"
     */
    public function testPropertyLuxuryLevelPrice()
    {
    }

    /**
     * Test attribute "number_sold"
     */
    public function testPropertyNumberSold()
    {
    }

    /**
     * Test attribute "estimated_repayments"
     */
    public function testPropertyEstimatedRepayments()
    {
    }

    /**
     * Test attribute "for_sale"
     */
    public function testPropertyForSale()
    {
    }

    /**
     * Test attribute "median_sold_price"
     */
    public function testPropertyMedianSoldPrice()
    {
    }

    /**
     * Test attribute "median_rent_price"
     */
    public function testPropertyMedianRentPrice()
    {
    }

    /**
     * Test attribute "days_on_market"
     */
    public function testPropertyDaysOnMarket()
    {
    }

    /**
     * Test attribute "bedrooms"
     */
    public function testPropertyBedrooms()
    {
    }

    /**
     * Test attribute "for_rent"
     */
    public function testPropertyForRent()
    {
    }

    /**
     * Test attribute "entry_level_price"
     */
    public function testPropertyEntryLevelPrice()
    {
    }

    /**
     * Test attribute "sales_growth_list"
     */
    public function testPropertySalesGrowthList()
    {
    }

    /**
     * Test attribute "auction_clearance_rate"
     */
    public function testPropertyAuctionClearanceRate()
    {
    }

    /**
     * Test attribute "property_category"
     */
    public function testPropertyPropertyCategory()
    {
    }

    /**
     * Test attribute "most_recent_sale"
     */
    public function testPropertyMostRecentSale()
    {
    }
}
