<?php
/**
 * DomainListingAdminServiceV1ModelBusinessListingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainListingAdminServiceV1ModelBusinessListingTest Class Doc Comment
 *
 * @category    Class
 * @description Business Listing
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainListingAdminServiceV1ModelBusinessListingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainListingAdminServiceV1ModelBusinessListing"
     */
    public function testDomainListingAdminServiceV1ModelBusinessListing()
    {
    }

    /**
     * Test attribute "listing_action"
     */
    public function testPropertyListingAction()
    {
    }

    /**
     * Test attribute "contact_preference"
     */
    public function testPropertyContactPreference()
    {
    }

    /**
     * Test attribute "under_offer_or_contract"
     */
    public function testPropertyUnderOfferOrContract()
    {
    }

    /**
     * Test attribute "nabers"
     */
    public function testPropertyNabers()
    {
    }

    /**
     * Test attribute "property_details"
     */
    public function testPropertyPropertyDetails()
    {
    }

    /**
     * Test attribute "lease_hold_details"
     */
    public function testPropertyLeaseHoldDetails()
    {
    }

    /**
     * Test attribute "sale_info"
     */
    public function testPropertySaleInfo()
    {
    }

    /**
     * Test attribute "freehold_commercial_ad_id"
     */
    public function testPropertyFreeholdCommercialAdId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "domain_ad_id"
     */
    public function testPropertyDomainAdId()
    {
    }

    /**
     * Test attribute "domain_agency_id"
     */
    public function testPropertyDomainAgencyId()
    {
    }

    /**
     * Test attribute "provider_ad_id"
     */
    public function testPropertyProviderAdId()
    {
    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "summary"
     */
    public function testPropertySummary()
    {
    }

    /**
     * Test attribute "inspection_details"
     */
    public function testPropertyInspectionDetails()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "other_enquiry_email"
     */
    public function testPropertyOtherEnquiryEmail()
    {
    }

    /**
     * Test attribute "receive_emails_to_default_address"
     */
    public function testPropertyReceiveEmailsToDefaultAddress()
    {
    }

    /**
     * Test attribute "is_rural"
     */
    public function testPropertyIsRural()
    {
    }

    /**
     * Test attribute "supplementary"
     */
    public function testPropertySupplementary()
    {
    }
}
