<?php
/**
 * DomainListingAdminServiceV1ModelResidentialPropertyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainListingAdminServiceV1ModelResidentialPropertyTest Class Doc Comment
 *
 * @category    Class
 * @description Residential Property
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainListingAdminServiceV1ModelResidentialPropertyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainListingAdminServiceV1ModelResidentialProperty"
     */
    public function testDomainListingAdminServiceV1ModelResidentialProperty()
    {
    }

    /**
     * Test attribute "property_type"
     */
    public function testPropertyPropertyType()
    {
    }

    /**
     * Test attribute "bed_rooms"
     */
    public function testPropertyBedRooms()
    {
    }

    /**
     * Test attribute "bath_rooms"
     */
    public function testPropertyBathRooms()
    {
    }

    /**
     * Test attribute "parking_info"
     */
    public function testPropertyParkingInfo()
    {
    }

    /**
     * Test attribute "energy_efficiency_rating"
     */
    public function testPropertyEnergyEfficiencyRating()
    {
    }

    /**
     * Test attribute "pdfs"
     */
    public function testPropertyPdfs()
    {
    }

    /**
     * Test attribute "is_marked_for_liveability"
     */
    public function testPropertyIsMarkedForLiveability()
    {
    }

    /**
     * Test attribute "property_name"
     */
    public function testPropertyPropertyName()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "land_area"
     */
    public function testPropertyLandArea()
    {
    }
}
