<?php
/**
 * DomainSearchServiceV2ModelDomainSearchContractsV2PropertyListingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainSearchServiceV2ModelDomainSearchContractsV2PropertyListingTest Class Doc Comment
 *
 * @category    Class
 * @description DomainSearchServiceV2ModelDomainSearchContractsV2PropertyListing
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainSearchServiceV2ModelDomainSearchContractsV2PropertyListingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainSearchServiceV2ModelDomainSearchContractsV2PropertyListing"
     */
    public function testDomainSearchServiceV2ModelDomainSearchContractsV2PropertyListing()
    {
    }

    /**
     * Test attribute "promo_level"
     */
    public function testPropertyPromoLevel()
    {
    }

    /**
     * Test attribute "listing_type"
     */
    public function testPropertyListingType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "advertiser"
     */
    public function testPropertyAdvertiser()
    {
    }

    /**
     * Test attribute "price_details"
     */
    public function testPropertyPriceDetails()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "property_details"
     */
    public function testPropertyPropertyDetails()
    {
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
    }

    /**
     * Test attribute "summary_description"
     */
    public function testPropertySummaryDescription()
    {
    }

    /**
     * Test attribute "has_floorplan"
     */
    public function testPropertyHasFloorplan()
    {
    }

    /**
     * Test attribute "has_video"
     */
    public function testPropertyHasVideo()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "auction_schedule"
     */
    public function testPropertyAuctionSchedule()
    {
    }

    /**
     * Test attribute "date_available"
     */
    public function testPropertyDateAvailable()
    {
    }

    /**
     * Test attribute "date_listed"
     */
    public function testPropertyDateListed()
    {
    }

    /**
     * Test attribute "inspection_schedule"
     */
    public function testPropertyInspectionSchedule()
    {
    }

    /**
     * Test attribute "sold_data"
     */
    public function testPropertySoldData()
    {
    }

    /**
     * Test attribute "listing_slug"
     */
    public function testPropertyListingSlug()
    {
    }
}
