<?php
/**
 * DomainAvmPIV1RentalEstimateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainAvmPIV1RentalEstimateTest Class Doc Comment
 *
 * @category    Class
 * @description DomainAvmPIV1RentalEstimate
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainAvmPIV1RentalEstimateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainAvmPIV1RentalEstimate"
     */
    public function testDomainAvmPIV1RentalEstimate()
    {
    }

    /**
     * Test attribute "weekly_rent_estimate"
     */
    public function testPropertyWeeklyRentEstimate()
    {
    }

    /**
     * Test attribute "percent_yield_rent_estimate"
     */
    public function testPropertyPercentYieldRentEstimate()
    {
    }

    /**
     * Test attribute "rental_fsd"
     */
    public function testPropertyRentalFsd()
    {
    }

    /**
     * Test attribute "estimate_date"
     */
    public function testPropertyEstimateDate()
    {
    }

    /**
     * Test attribute "property_type"
     */
    public function testPropertyPropertyType()
    {
    }
}
