<?php
/**
 * DomainListingAdminServiceV1ModelMedianPriceDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DomainListingAdminServiceV1ModelMedianPriceDataTest Class Doc Comment
 *
 * @category    Class
 * @description Information regarding median house/unit price   for the suburb
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainListingAdminServiceV1ModelMedianPriceDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainListingAdminServiceV1ModelMedianPriceData"
     */
    public function testDomainListingAdminServiceV1ModelMedianPriceData()
    {
    }

    /**
     * Test attribute "price_type"
     */
    public function testPropertyPriceType()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "median_price"
     */
    public function testPropertyMedianPrice()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "source_date_from"
     */
    public function testPropertySourceDateFrom()
    {
    }

    /**
     * Test attribute "source_date_to"
     */
    public function testPropertySourceDateTo()
    {
    }

    /**
     * Test attribute "declaration_text"
     */
    public function testPropertyDeclarationText()
    {
    }
}
