<?php
/**
 * ListingAdminV2SpecificUnitDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ListingAdminV2SpecificUnitDetailTest Class Doc Comment
 *
 * @category    Class
 * @description offered units details
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingAdminV2SpecificUnitDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListingAdminV2SpecificUnitDetail"
     */
    public function testListingAdminV2SpecificUnitDetail()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "is_sold_or_leased"
     */
    public function testPropertyIsSoldOrLeased()
    {
    }

    /**
     * Test attribute "occupancy"
     */
    public function testPropertyOccupancy()
    {
    }

    /**
     * Test attribute "price_unit"
     */
    public function testPropertyPriceUnit()
    {
    }

    /**
     * Test attribute "lease_price_for_saleor_lease"
     */
    public function testPropertyLeasePriceForSaleorLease()
    {
    }
}
