<?php
/**
 * ListingsV2ProjectAddressPartsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ListingsV2ProjectAddressPartsTest Class Doc Comment
 *
 * @category    Class
 * @description Project address parts
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingsV2ProjectAddressPartsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListingsV2ProjectAddressParts"
     */
    public function testListingsV2ProjectAddressParts()
    {
    }

    /**
     * Test attribute "state_abbreviation"
     */
    public function testPropertyStateAbbreviation()
    {
    }

    /**
     * Test attribute "display_type"
     */
    public function testPropertyDisplayType()
    {
    }

    /**
     * Test attribute "street_number"
     */
    public function testPropertyStreetNumber()
    {
    }

    /**
     * Test attribute "unit_number"
     */
    public function testPropertyUnitNumber()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "suburb_id"
     */
    public function testPropertySuburbId()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "display_address"
     */
    public function testPropertyDisplayAddress()
    {
    }

    /**
     * Test attribute "street2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }
}
