<?php
/**
 * SchoolsV2SchoolProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * SchoolsV2SchoolProfileTest Class Doc Comment
 *
 * @category    Class
 * @description SchoolProfile
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SchoolsV2SchoolProfileTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SchoolsV2SchoolProfile"
     */
    public function testSchoolsV2SchoolProfile()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "year_range"
     */
    public function testPropertyYearRange()
    {
    }

    /**
     * Test attribute "icsea"
     */
    public function testPropertyIcsea()
    {
    }

    /**
     * Test attribute "bottom_sea_quarter"
     */
    public function testPropertyBottomSeaQuarter()
    {
    }

    /**
     * Test attribute "lower_middle_sea_quarter"
     */
    public function testPropertyLowerMiddleSeaQuarter()
    {
    }

    /**
     * Test attribute "upper_middle_sea_quarter"
     */
    public function testPropertyUpperMiddleSeaQuarter()
    {
    }

    /**
     * Test attribute "top_sea_quarter"
     */
    public function testPropertyTopSeaQuarter()
    {
    }

    /**
     * Test attribute "total_enrolments"
     */
    public function testPropertyTotalEnrolments()
    {
    }

    /**
     * Test attribute "girls_enrolments"
     */
    public function testPropertyGirlsEnrolments()
    {
    }

    /**
     * Test attribute "boys_enrolments"
     */
    public function testPropertyBoysEnrolments()
    {
    }
}
