<?php
/**
 * StatisticsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: latest
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StatisticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatisticsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for statisticsPost
     *
     * Record a statistic event along with its associated metadata (if applicable).
     *
     */
    public function testStatisticsPost()
    {
    }

    /**
     * Test case for suburbPerformanceGetByNamedSuburb
     *
     * Search for sales statistics in a given geographic level..
     *
     */
    public function testSuburbPerformanceGetByNamedSuburb()
    {
    }

    /**
     * Test case for suburbPerformanceGetByNamedSuburbWithoutPostcode
     *
     * Search for sales statistics in a given geographic level..
     *
     */
    public function testSuburbPerformanceGetByNamedSuburbWithoutPostcode()
    {
    }
}
